config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'static#home'
  get 'homepage', to:'static#homepage'
  get 'myproject', to:'projects#ongoing_project'
  get 'tags/:tag', to: 'projects#index', as: :tag
  get 'aboutus', to:'static#aboutus'

  resources :posts do
    resources :comments
  end

  resources :users, only: [:show] do
    resources :avatars, only: [:new, :create]
  end

  resources :projects, only: [:edit] do
    resources :images, only: [:new, :create]
  end


  resources :users do
    resources :skill_setups
  end

  resources :projects do
    resources :charges, path: 'paiement'
    resources :attendances, path: 'inscription'
  end

    namespace :admin do
    root 'admin#index'
    resources :users, :projects, :project_submissions
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user


  validates :comment,
  presence: true,
  length: { in: 1..1000}


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :my_comment, only: [:edit, :update, :destroy]


  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(user: current_user, post: @post, comment: params[:comment])

    if @comment.save
     redirect_to myproject_path(anchor: 'chat')
    else
     render 'new'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment: params[:comment])

    if @comment.save
      redirect_to myproject_path(anchor: 'chat')
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to myproject_path(anchor: 'chat')
  end

  private

  def my_comment
    @comment = Comment.find(params[:id])
    unless current_user == @comment.user
      flash[:error] ="Vous n'êtes pas autorisé à consulter cette page"
      redirect_to myproject_path(anchor: 'chat')
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<div class="row comment-section text-wrap">
	<div class="col-md-4">
		<p>Avatar auteur</p>
		<p>De <%= post.user.first_name.capitalize %> <%= post.user.last_name[0].capitalize %></p>
	</div>

	<div class="col-md-8 px-3">
		
		<div class="form-group">
			<div class="field mx-4 my-5 px-4 text-wrap">
				<p><%= comment.comment %></p>
				<i class="text-muted">Publié le <%= comment.created_at.strftime("%d/%m/%Y à %I:%M") %></i>
			</div>
			<div class="field mx-4 my-5 px-4 row">
				<% if comment.user == current_user %>
				<div class="col-10 text-right">
					<%= button_to 'Modifier', edit_post_comment_path(post.id, comment.id), method: 'get', class:'btn btn-sm btn-warning'%>
				</div>
				<div class="col-2 text-right">
					<%= button_to 'Supprimer', post_comment_path(post.id, comment.id), method: :delete, class:'btn btn-sm btn-danger', data: { confirm: "Souhaites-tu vraiment supprimer ce commentaire ?" }%>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/comments/_form.html.erb
<div class="row ">
	<div class="col-md-12 grey-box px-3">
		<div class="form-group">
			<%= form_tag(post_comments_path(post.id), :action => "create", :method => "post") do %>
			<div class="field mx-4  px-4">
				<%= text_area_tag :comment, nil, placeholder:'Commentaire',size: "14x2",class:'form-control smallform'%>
			</div>
			<div class="field mx-4 my-2 px-4">
				<%= submit_tag "Commenter", class: "btn btn-primary"%>
			</div>
			<% end %>
			<hr>
		</div>

	</div>

</div>

app/views/comments/edit.html.erb
<div class="row ">
	<div class="col-md-2"></div>
	<div class="col-md-10 grey-box px-3">
		<div class="form-group">
			<h6 class="mx-4 my-4 px-2 py-2">Modifier un commentaire</h6>

			<%= form_tag(post_comment_path(@post.id, @comment.id), :action => "update", :method => "patch") do %>
			<div class="field mx-4  px-4">
				<%= text_area_tag :comment, @comment.comment, placeholder:'Commentaire',size: "14x2",class:'form-control smallform'%>
			</div>
			<div class="field mx-4 my-2 px-4">
				<%= submit_tag "Confirmer la modification", class: "btn btn-primary"%>
			</div>
			<% end %>
		</div>
	</div>
</div>