config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'static#home'
  get 'homepage', to:'static#homepage'
  get 'myproject', to:'projects#ongoing_project'
  get 'tags/:tag', to: 'projects#index', as: :tag
  get 'aboutus', to:'static#aboutus'

  resources :posts do
    resources :comments
  end

  resources :users, only: [:show] do
    resources :avatars, only: [:new, :create]
  end

  resources :projects, only: [:edit] do
    resources :images, only: [:new, :create]
  end


  resources :users do
    resources :skill_setups
  end

  resources :projects do
    resources :charges, path: 'paiement'
    resources :attendances, path: 'inscription'
  end

    namespace :admin do
    root 'admin#index'
    resources :users, :projects, :project_submissions
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :skill_setups, dependent: :destroy
  has_many :skills, through: :skill_setups
  has_many :attendances, foreign_key: 'attendee_id', dependent: :destroy
  has_many :projects, through: :attendances
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :avatar


  # after_create :welcome_send


  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end


  def is_available?(project)
    attendee_projects = Attendance.where(attendee: self)
    owner_projects = Project.where(owner: self)
    project_dates = (project.start_date.strftime("%d/%m/%Y").to_datetime..project.end_date.strftime("%d/%m/%Y").to_datetime)

    unavailable_dates = []

    attendee_projects.each do |attendance|
      (attendance.project.start_date.strftime("%d/%m/%Y").to_datetime..attendance.project.end_date.strftime("%d/%m/%Y").to_datetime).each do |date|
        unavailable_dates << date
      end
    end

    owner_projects.each do |project_o|
      (project_o.start_date.strftime("%d/%m/%Y").to_datetime..project_o.end_date.strftime("%d/%m/%Y").to_datetime).each do |date|
        unavailable_dates << date
      end
    end

    if project_dates.any? {|project_date| unavailable_dates.include?(project_date) }
      return false
    else
      return true
    end

  end

  def ongoing_project

    projects_as_attendee = Attendance.where(attendee: self, state: "paid").map {|a| a.project }.compact
    projects_as_owner = Project.where(owner: self, state: "published").map {|project| project }.compact

    projects = projects_as_attendee + projects_as_owner

    if projects.length > 0
      projects.map {|project| project.ongoing? ? project : nil }.compact
    end
  end


  def thumbnail
    return self.avatar.variant(resize: "200x200!")
  end


  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.all.order("created_at DESC")
  end

  def show
    @user = User.find(params[:id])
    @projects_o = Project.where(owner: @user, state: "published") + Project.where(owner: @user, state: "paid") + Project.where(owner: @user, state: "finished")
    @project_a = Project.where(attendee: @user, state: "paid")
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
      if @user.update(first_name: params[:first_name], last_name: params[:last_name], email: params[:email])
        flash[:success] = "Les informations ont été modifiées"
        redirect_to admin_user_path
      else
        flash[:alert] = "Les informations n'ont pas été modifiées"
        redirect_to admin_user_path
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
    flash.alert = "Le participant #{params[:id]} a bien été supprimé !"
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
    new_user_skill_setup_path(@user.id)
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_my_profile, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @attendances = Attendance.where(attendee: @user) 
    @projects = Project.where(owner: @user)
    @skill_setup_primary = SkillSetup.find_by(user: @user, primary: true)
    @skill_setup_secondary = SkillSetup.find_by(user: @user, primary: false)
  end

  def edit
    @user = User.find(params[:id])
    @attendances = Attendance.where(attendee: current_user) 
    @projects = Project.where(owner: current_user)
    @skills = Skill.all
    @skill_setup_primary = SkillSetup.find_by(user: current_user, primary: true)
    @skill_setup_secondary = SkillSetup.find_by(user: current_user, primary: false)
  end

  def update
    @user = User.find(params[:id])
      if @user.update(first_name: params[:first_name], last_name: params[:last_name], email: params[:email])
        flash[:success] = "Vos informations personnelles ont été modifiées"
        redirect_to @user
      else
        flash[:alert] = "Vos informations personnelles n'ont pas été modifiées"
        redirect_to @user
      end
  end


  private

def not_my_profile
  @user = User.find(params[:id])
  unless current_user == @user
    flash[:error] ="Vous n'êtes pas autorisé à consulter cette page. Voici la page publique du membre."
      redirect_to @user
  end
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_attendance_user.html.erb
<div class="container bootstrap snippet my-5">
<h3>Les projets auxquels je participe :</h3>
<% if @attendances[0] %>
    <div class="row my-4">
        <% @attendances.each do |attendance| %>
        <div class="col-sm-4 my-2">
            <div class="card text-dark bg-light mb-4" style="max-width: 20rem;">
              <%= link_to project_path(attendance.project.id) do %>
                <div class="card-header font-weight-bold"> <h4> <%= attendance.project.title.capitalize%> </h4> </div>
              <% end %>
                <div class="card-body">
                    <p class="text"><%=attendance.project.start_date.strftime("Le %d/%m/%Y à %I:%M")%></p>
                </div>
                <div class="card-body">
                <%= button_to "Voir", project_path(attendance.project.id), method: 'get', class:"btn btn-sm btn-secondary"%>
                </div>
            </div>
        </div>
        <% end %>
    </div>
    <% else %>
        <p class="my-5">Vous n'êtes inscrit à aucun projet pour le moment.</p>
        <% end%>
    <hr>
</div>

 

app/views/users/_edit_form.html.erb
<div class="container bootstrap snippet my-5">
<%= form_tag url_for(action: 'update'), method: "patch", id:"editForm", authenticity_token: true do %>
        <h3>Modifier mes informations</h3>
        <div class="form-group">
            <div class="col-xs-6">
              <%= label_tag 'Prénom :' %>
              <%= text_field_tag :first_name, @user.first_name, class:'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-6">
              <%= label_tag 'Nom :' %>
              <%= text_field_tag :last_name, @user.last_name, class:'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-6">
              <%= label_tag 'Email :' %>
              <%= text_field_tag :email, @user.email, class:'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                  <br>
                  <%= submit_tag "Modifier mes informations personnelles", class:"btn btn-dark" %>
            </div>
        </div>
      <% end %>
  </div>     
  <hr>
<div class="container bootstrap snippet my-5">
  <h3 class="my-3">Vos compétences :</h3>
  <h6>Compétence principale: </h6>
  <%= render 'primary_skill_form'%>

  <h6>Compétence secondaire: </h6>
  <%= render 'secondary_skill_form'%>
</div>
<hr>

app/views/users/_edit_picture.html.erb
<div class="text-center m-4 p-3">

  <% if @user.avatar.attached? %>
    <%= image_tag url_for(@user.thumbnail), alt: 'avatar', class: "avatar img-circle img-thumbnail" %>
    <div class="mt-4 mb-4">
      <%= link_to "Voir votre profil public", user_path(current_user.id), :class =>"btn btn-sm btn-primary" %>
    </div>
  <% else %>
    <%= image_tag asset_path("avatar_2x.png"), class:"avatar-small img-circle img-thumbnail my-3", alt:"avatar"%>
  <%end%>
  <h6 class='mt-5 mb-4'>Changer votre photo :</h6>
  <%= form_tag user_avatars_path(@user), multipart: true do %>
    <div class="my-3">
      <%= file_field_tag :avatar%>
    </div>
    <div class="my-3">
      <%= submit_tag "Enregistrer", class: "btn btn-dark" %>
    </div>
  <% end %>
</div>

app/views/users/_my_profile.html.erb
<div class="container bootstrap snippet mt-4 mb-5">
  <br>
  <div class="row m-4">
  <div class="col-sm-12"><h1>Bienvenue sur votre compte <%= @user.first_name.capitalize %>,</h1></div>
  </div>
  <div class="row mt-2 mb-5">
    <div class="col-sm-4">
    <%= render 'edit_picture', user: @user %>
    </div>
    <div class="col-sm-8">
        <ul class="nav my-5">
              <li class="nav-item active" role="presentation"><a href="#settings" aria-controls="settings" class="btn btn-light active" data-toggle="tab">Mes informations</a></li>
              <li class="nav-item" role="presentation"><a href="#myprojects" aria-controls="myprojects" class="btn btn-light" data-toggle="tab">Mes projets</a></li>
              <li class="nav-item" role="presentation"><a href="#myattendances" aria-controls="myattendances" class="btn btn-light" data-toggle="tab">Mes sessions</a></li>
              <li class="nav-item" role="presentation"><a href="#myorders" aria-controls="myorders" class="btn btn-light" data-toggle="tab">Mes paiements</a></li>
        </ul>
        <div class="tab-content">
           <div role="tabpanel" class="tab-pane active fade-in" id="settings">
            <%= render 'edit_form', user: @user %>
           </div>

           <div role="tabpanel" class="tab-pane fade" id="myprojects"> 
            <%= render 'project_user', projects: @projects %>
           </div>

           <div role="tabpanel" class="tab-pane fade" id="myattendances">
           <%= render 'attendance_user', attendances: @attendances %>
           </div>

           <div role="tabpanel" class="tab-pane fade" id="myorders">
            <%= render 'payment', attendances: @attendances %>
           </div>
        </div>
      </div>
  </div>
</div>

app/views/users/_payment.html.erb
<div class="container bootstrap snippet my-5">

    <% if @attendances.length < 1 %>
    <%= link_to "Ici pour s'inscrire", projects_path, :class =>"btn btn-sm btn-secondary" %>

    
<%else%>
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Nom du projet</th>
                <th>État du projet</th>
                <th>Date de commande</th>
                <th>Montant réglé</th>
                        
            </tr>
        </thead>

        <tbody>
        <% @attendances.each do |attendance| %>
            <tr>
                <td><%= attendance.project.title %></td>
                <td><%= attendance.state %></td>
                <td><%= attendance.created_at.strftime("%d/%m/%Y") %></td>
                <td><%= attendance.price_attendee.to_f / 100 %></td>
                        
            </tr>
        <%end%>
        </tbody>

        </table>
<%end%>
   
</div>

app/views/users/_primary_skill_form.html.erb
<div class="container bootstrap snippet my-4">
<% if @user.skills.length == 0 %>
	<p>A quel métier vos compétences correspondent-elles le plus ? </p>
	<%= form_tag(user_skill_setups_path(@user.id), :action => "create", :method => "post") do %>
		<%= hidden_field_tag :primary, true %>
		<%= select_tag(:skill_id, options_for_select(@skills.map {|skill| [skill.title, skill.id] }), :include_blank => true )%>
		<%= submit_tag "Enregistrer", class: "btn btn-primary mx-4"%>
	<%end%>	

<% elsif @user.skills.length >= 1 %>
<p>Vous avez choisi la compétence : <span class ="text-primary font-weight-bold"><%=@skill_setup_primary.skill.title%></span></p>
	<%= form_tag(user_skill_setup_path(@user.id, @skill_setup_primary.id), :action => "update", :method => "patch") do %>
		<%= hidden_field_tag :primary, true %>
		<%= select_tag(:skill_id, options_for_select(@skills.map {|skill| [skill.title, skill.id] }), :include_blank => true, :prompt => @skill_setup_primary.skill.title )%>
		<%= submit_tag "Modifier", class: "btn btn-dark mx-4"%>
	<%end%>

<% end %>
</div>

app/views/users/_profile_page.html.erb
<div class="row mt-0">
  <div class="col-lg-12">
        <div class="jumbotron-user jumbotron-user-fluid mt-0 ">
            <div class="mx-5 my-5 pt-0 px-5 d-flex justify-content-start align-items-center">
              <% if @user.avatar.attached? %>
                <%= image_tag url_for(@user.thumbnail), alt: 'avatar' %>
              <% else %>
                <%= image_tag asset_path("avatar_2x.png"), class:"avatar-small img-circle img-thumbnail my-3", alt:"avatar"%>
              <%end%>
              <h1 class="mt-1 mb-1 mx-3 text-light"><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></h1>
              <div class="mx-5 my-1 d-flex justify-content-end">
              <% if current_user == @user %>
              <%= link_to "Modifier", edit_user_path(current_user.id), :class =>"btn btn-sm btn-dark" %>
              <% end %>
            </div>
            </div>
        </div>
<div class="row my-2">
  <div class="col-md-4 p-4">
    <div class="text-center shadow m-4 p-4">
      <h5><i class="fas fa-user-cog" style="margin-right: 8px;"></i> Ses compétences :</h5>
      <% if @skill_setup_primary %>
      <p><%= @skill_setup_primary.skill.title %></p>
      <% else %>
      <p>Ce membre n'a pas encore indiqué ses compétences.</p>
        <% if current_user %>
        <%= link_to "Modifier", edit_user_path(current_user.id), :class =>"btn btn-sm btn-dark" %>
        <% end %>
      <%end%>
      <% if @skill_setup_secondary %>
      <p><%= @skill_setup_secondary.skill.title %></p>
      <%end%>
    </div>
  </div>
  <div class="col-md-8 p-4 ">
    <div class="px-5 pt-2 pb-5 mr-4">
      <h5 class='my-4'>Les projets que ce membre a proposé :</h5>
      <% if @projects[0] %>
      <div class="row">
            <% @projects.each do |project| %>
            <% if project.state == "published" %>
              <div class="col-sm-4">
                  <div class="card text-dark bg-light mb-3" style="max-width: 20rem;">
                      <div class="card-header">Projet : <%= project.title.capitalize%><br></div>
                      <div class="card-body">
                          <p class="card-text"><%= project.start_date.strftime("Le %d/%m/%Y à %I:%M")%></p>
                          <%= link_to "Voir le projet", project_path(project.id), :class =>"btn btn-sm btn-dark" %>
                      </div>
                  </div>
              </div>
              <% end %>
            <% end %>
          </div>
        <% else %>
          <% if @user == current_user %>
            <p class="text-secondary">Vous n'avez proposé aucun projet pour le moment.</p>
            <%= render 'layouts/CTA_projectnew' %> 
            <%else%>
            <p class="text-secondary">Ce membre n'a proposé aucun projet pour le moment.</p>
          <%end%>
        <%end%>
        <hr class="my-4">
        <h5 class='my-4'>Les projets auxquels ce membre a participé :</h5>
        <% if @attendances[0] %>
            <% @attendances.each do |attendance| %>
            <% if attendance.project.state == "published" %>
            <div class="col-sm-2">
                <div class="card text-dark bg-light mb-3" style="max-width: 20rem;">
                    <div class="card-header"><%= attendance.project.title.capitalize%><br></div>
                    <div class="card-body">
                        <p class="card-text"><%= attendance.project.start_date.strftime("Le %d/%m/%Y à %I:%M")%></p>
                    </div>
                </div>
            </div>
            <%end%>
          <%end%>
        </div>
      <% else %>
        <% if @user == current_user %>
          <p class="text-secondary">Vous n'avez participé à aucun projet pour le moment.</p>
          <%= render 'layouts/CTA_attendee' %> 
        <%else%>
          <p class="text-secondary">Ce membre n'a participé à aucun projet pour le moment.</p>
        <%end%>
      <%end%>
    </div>
  </div>
</div>

app/views/users/_project_user.html.erb
<div class="container bootstrap snippet my-5">
<h3>Les projets dont je suis l'organisateur :</h3>
<% if @projects[0] %>
    <div class="row my-4">
        <% @projects.sort_by(&:start_date).each do |project| %>
        <div class="col-sm-6 my-2">
            <div class="card text-dark bg-light mb-3" style="max-width: 20rem;">
                <%= link_to project_path(project.id) do %>
                  <div class="card-header font-weight-bold"> <h4> <%= project.title.capitalize%> </h4> </div>
                <% end %>
                <div class="card-body">
                  <p class="card-text"><span class="font-weight-bold">Date :</span> <%= project.start_date.strftime("%d/%m/%Y à %I:%M")%></p>
                  <p class="card-text"><span class="font-weight-bold">Etat du projet :</span> <%= project.state%></p>
                </div>
                <div class="card-body">
                <%= button_to "Poursuivre", edit_project_path(project.id), method: 'get', class:"btn btn-sm btn-secondary"%>
                </div>
            </div>
        </div>
        <% end %>
    </div>  

    <% else %>
    <p class="my-5">Vous n'avez proposé aucun projet pour le moment.</p>
    <% end%>
    <hr>

</div>

 

app/views/users/_secondary_skill_form.html.erb
<div class="container bootstrap snippet my-4">

<% if @user.skills.length == 0 %>
<p>Il faut choisir une compétence principale avant d'en choisir une seconde !</p>
<% elsif @user.skills.length == 1 %>
	<%= form_tag(user_skill_setups_path(@user.id), :action => "create", :method => "post") do %>
		<%= hidden_field_tag :primary, false %>
		<%= select_tag(:skill_id, options_for_select(@skills.map {|skill| [skill.title, skill.id] }), :include_blank => true)%>
		<%= submit_tag "Enregistrer", class: "btn btn-primary mx-4"%>
	<%end%>

<% elsif @user.skills.length == 2 %>
<p>Vous avez choisi la compétence : <span class ="text-primary font-weight-bold"><%=@skill_setup_secondary.skill.title%></span></p>
	<%= form_tag(user_skill_setup_path(@user.id, @skill_setup_secondary.id), :action => "update", :method => "patch") do %>
		<%= hidden_field_tag :primary, false %>
		<%= select_tag(:skill_id, options_for_select(@skills.map {|skill| [skill.title, skill.id] }), :include_blank => true, :prompt => @skill_setup_secondary.skill.title)%>
		<%= submit_tag "Modifier", class: "btn btn-dark mx-4"%>
	<%end%>

<% end %>
</div>

app/views/users/edit.html.erb
<%= render 'my_profile', user: @user %>

app/views/users/show.html.erb
<%= render 'profile_page', user: @user %>