config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'static#home'
  get 'homepage', to:'static#homepage'
  get 'myproject', to:'projects#ongoing_project'
  get 'tags/:tag', to: 'projects#index', as: :tag
  get 'aboutus', to:'static#aboutus'

  resources :posts do
    resources :comments
  end

  resources :users, only: [:show] do
    resources :avatars, only: [:new, :create]
  end

  resources :projects, only: [:edit] do
    resources :images, only: [:new, :create]
  end


  resources :users do
    resources :skill_setups
  end

  resources :projects do
    resources :charges, path: 'paiement'
    resources :attendances, path: 'inscription'
  end

    namespace :admin do
    root 'admin#index'
    resources :users, :projects, :project_submissions
  end

end

app/models/project.rb
class Project < ApplicationRecord
  include AASM
  belongs_to :owner, foreign_key: 'owner_id', class_name: "User"
  belongs_to :package
  has_many :attendances, dependent: :destroy
  has_many :attendees, class_name: "User", through: :attendances
  has_one_attached :image
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  # after_update :confirmation_email


  validates :title,
  presence: true,
  length: { in: 3..100}

  validates :short_description,
  presence: true,
  length: { in: 5..140}

  validates :attendees_goal,
  presence: true,
  numericality: { greater_than: 1, less_than: 6 }
  
  aasm column: :state do
    state :draft, initial: true
    state :submitted
    state :paid
    state :published
    state :finished

    event :submit do
      transitions from: :draft, to: :submitted
    end
    event :pay do
      transitions from: :submitted, to: :paid
    end
    event :publish do
      transitions from: :paid, to: :published
    end
    event :unpublish do
      transitions from: :published, to: :paid
    end
    event :end do
      transitions from: :published, to: :finished
    end
  end



  def ongoing?
      self.start_date <= Time.zone.now && self.end_date >= Time.zone.now
  end

  def end_date
    self.start_date + (self.package.number_of_days * 86400)
  end

  def confirmation_email
    if self.state == "paid"
      UserMailer.confirmation_charge_email(self, self.owner).deliver_now
    elsif self.state == "published" 
      UserMailer.project_published_email(self, self.owner).deliver_now
      UserMailer.reminder_participation_email(self, self.owner).deliver_later(wait_until: (self.start_date - 259200))

      self.attendees.each do |attendee|
        UserMailer.reminder_participation_email(self, attendee).deliver_later(wait_until: (self.start_date - 259200))
      end
    end
  end

  def banner
    return self.image.variant(resize: "770x433!")
  end
  
  def full?
    if self.attendees.length.to_i >= self.attendees_goal.to_i
      return true
    else
      return false
    end
  end

  def self.tagged_with(name)
    Tag.find_by!(name: name).projects
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController

  def index
    @projects = Project.all.order("created_at DESC")
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
   @project = Project.find(params[:id])
 end

 def update
  @project = Project.find(params[:id])

  @project.update(project_params)
  @start_date = Time.parse(params[:project].to_s)
  @project.update(start_date: @start_date)


  if @project.save
    flash[:success] = "Le projet a été modifié !"
    redirect_to admin_project_path(@project.id)
  else
   flash.now[:error] = @project.errors.full_messages.to_sentence
   render :edit
 end
end

def destroy
  @project = Project.find(params[:id])
  @project.destroy
  redirect_to admin_projects_path
  flash.alert = "Le projet #{params[:id]} a bien été supprimé !"
end

private

def project_params
  params.permit(:title, :short_description, :long_description, :attendees_goal)
end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :my_project, only: [:edit, :update]
  before_action :ongoing, only: [:ongoing_project]
  
  def index
    params[:tag] ? @projects = Project.tagged_with(params[:tag]) : @projects = Project.all
    @tags = Tag.all
  end

  def show
    @project = Project.find(params[:id])
    @user_attendance = Attendance.find_by(attendee: current_user, project: @project)
    @skill_primary = SkillSetup.find_by(user: @project.owner, primary: true)
    @skill_secondary = SkillSetup.find_by(user: @project.owner, primary: false)
  end
   
  def new
    @project = Project.new
    @packages = Package.all
 
  end

  def create
    @user = current_user
    @project = Project.new(project_params)
    @start_date = Time.new(params[:project]["start_date(1i)"],params[:project]["start_date(2i)"],params[:project]["start_date(3i)"],params[:project]["start_date(4i)"],params[:project]["start_date(5i)"])
    @project.update(start_date: @start_date)
    @packages = Package.all

    if @project.save
      flash[:success] = "Le projet a été créé !"
      redirect_to @project
    else
     flash.now[:error] = @project.errors.full_messages.to_sentence
     render :new
    end

  end

  def edit
    @packages = Package.all
    @project = Project.find(params[:id])
  end

  def update
    @packages = Package.all
    @project = Project.find(params[:id])
    @project.update(project_params)
    @start_date = Time.new(params[:project]["start_date(1i)"],params[:project]["start_date(2i)"],params[:project]["start_date(3i)"],params[:project]["start_date(4i)"],params[:project]["start_date(5i)"])
    @project.update(start_date: @start_date)

    if params[:publish] == "Soumettre mon projet"
      @project.submit_date = Time.zone.now
      @project.submit!
      if @project.save
        flash[:alert] = "Pour que le projet soit publié, le paiement doit être effectué"
        redirect_to new_project_charge_path(@project.id)
      else
       flash.now[:error] = @project.errors.full_messages.to_sentence
       render :edit
      end
    else
      if @project.save
        flash[:success] = "Le projet a été modifié !"
        redirect_to project_path(@project.id)
      else
       flash.now[:error] = @project.errors.full_messages.to_sentence
       render :edit
      end
    end
  end 


  def ongoing_project
    @project = current_user.ongoing_project[0]
    @posts = Post.where(project: @project).order("created_at DESC")
    @attendees = @project.attendees
    render layout: "layouts/ongoing_project"
  end


private

  def project_params
    params.permit(:owner_id, :package_id, :title, :short_description, :long_description, :attendees_goal, :tag_list, :tag, { tag_ids: [] }, :tag_ids)
  end


  def my_project
    @project = Project.find(params[:id])
    unless current_user == @project.owner
      flash[:error] ="Vous n'êtes pas autorisé à consulter cette page"
      redirect_to root_path
    end
  end

  def ongoing
    unless user_signed_in? && (attendance(current_user) == true || ownership(current_user) == true) && current_user.ongoing_project != nil

      flash[:alert] ="Aucun projet en cours, n'hésitez pas à vous inscrire !"
      redirect_to projects_path
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def attendance(project)
    if Attendance.find_by(attendee: current_user, project: project)
      return true
    end
  end

  
end

app/views/projects/_chat.html.erb
	<div class="tab-pane " id="chat">
		<%= render 'posts/index' %>
	</div>

app/views/projects/_group.html.erb
<div class="tab-pane pb-5" id="group">
	<div class="container-fluid">
		<div class="card no-border">
			<div class="card-body my-4">
				<h5 class="card-title">Participants au projet "<%= @project.title %>"</h5>

				<p class="card-text"><%= @project.owner.first_name.capitalize %> : <%= @project.owner.email %> <span class="text-muted">(Porteur du projet)</span> </p>
				<% @attendees.each do |a| %>
				<p class="card-text"><%= a.first_name.capitalize %> : <%= a.email %></p>
				<%end%>
			</div>
		</div>
	</div>
</div>

app/views/projects/_introduction.html.erb
	<div class="tab-pane active px-4 pb-5" id="intro">
		<h3 class="my-4">C'est parti !</h3>
		<p>Le porteur du projet va commencer par tous vous contacter afin d'organiser un premier call pour vous pitcher son projet.</p>
		<p>Tu trouveras dans les ressources nos conseils pour réussir ce projet, nos outils favoris pour collaborer en remote, les étapes clés de la construction d'un projet...</p>
	</div><!--/tab-pane-->

app/views/projects/_ownerproject.html.erb
<h2 class="my-3"> Mon espace admin</h2>
<table class="table shadow p-3 mb-5 bg-white rounded">

  <tbody>
    <tr>
      <th scope="row" class="text-secondary"> <h6> Nom de mon projet </h6> </th>
      <td class="text-secondary"> <%= @project.title.capitalize %> </td>
    </tr>

    <tr>
      <th scope="row" class="text-secondary"> <h6> Nom des participants et <br> leurs compétences </h6> </th>
      <td class="text-secondary"> <% @project.attendees.each do |participant|%>
        <% if @project.attendees.length > 0  %>
        <p> 
          <%= participant.first_name %> <%=participant.last_name.capitalize %> - 
          <% if participant.skills.length > 0 %>
          <%= primary_skill(participant) %>
        </p>
        <%end%>
        <% else %>
        <p> Aucun participant pour le moment </p>
        <% end %>

        <% end %>
      </td>
    </tr>

    <tr>
      <th scope="row" class="text-secondary"> <h6> Nombre de participants </h6> </th>
      <td class="text-secondary"> <%= @project.attendees.length.to_i %> </td>
    </tr>

    <tr>
      <th scope="row" class="text-secondary"> <h6> Dates de mon projet </h6> </th>
      <td class="text-secondary">
        <p>Commence le <%= @project.start_date.strftime("%d/%m/%Y à %I:%M") %> </p>
        <p>Termine le <%= @project.end_date.strftime("%d/%m/%Y à %I:%M") %> </p>
      </td>
    </tr>

    <tr>
      <th scope="row" class="text-secondary"> <h6> Etat de mon projet</h6> </th>
      <td class="text-secondary">  
        <p class="mb-3"><%= @project.state %></p>
        <%if @project.state == "draft" ||  @project.state == "submitted"%>
          <p><%= button_to "Modifier mon projet", edit_project_path(@project.id), method: 'get', class:"btn btn-secondary" %></p>
        <%else%>
          <p> Votre projet a été déjà publié et ne peut plus être modifié.<p>
        <%end%>
        </td>
      </tr>

    </tbody>
  </table>

app/views/projects/_project_card.html.erb
  <div class="col-md-4 my-4"> 
    <div class="card shadow-sm">
      <%= link_to project_path(project.id) do %>
        <%if project.image.attached?%>
          <%= image_tag url_for(project.banner), alt: 'project image', class:"w-100" %>
        <%else%>
          <%= image_tag asset_path('photo-1531297484001-80022131f5a1.jpg'), alt: "runstart", class:"w-100" %>   
        <%end%>
      <%end%>
      <p class="my-0 mx-3 overlay"><small><%= raw project.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(' ') %></small></p>
      <div class="card-body">
          <h5 class="card-title"><%= project.title%></h5>
          <h6 class="card-title"><%= project.start_date.strftime("le %d/%m/%Y à %I:%M")%></h6>
          <p class="card-text"><%= project.short_description.truncate(100) %></p>

          <div class="d-flex justify-content-between align-items-center">
            <%if project.state == "published" %>
            <% if project.full? %>
              <p> COMPLET </p>
            <% elsif user_signed_in? %>
              <% if attendance(project) == true %>
                <h6>Déjà inscrit !</h6>
              <% elsif current_user.is_available?(project) == false %>
                <p></p>
              <% else %>
                <%= button_to "S'inscrire", new_project_attendance_path(project.id), method: 'get', class:"btn btn-primary"%>
              <% end %>
            <% else %>
                <%= button_to "S'inscrire", new_project_attendance_path(project.id), method: 'get', class:"btn btn-primary"%>
            <% end %>
           <%end%>
            <%= link_to "En savoir plus", project_path(project.id), :class =>"btn btn-sm btn-dark" %>
            <div class="text-muted"> 
              <small><%= project.attendees.count%> inscrits</small>
            </div>
          </div>
      </div>
    </div>
  </div>

app/views/projects/_projectslist.html.erb
<div class="album py-5 mt-0 bg-light">
    <div class="row">
    <div class="col-md-2">
    <p class="mx-4 mt-5 mb-1 font-weight-bold text-uppercase"> Trier par </p>
    <div class="filter-box mt-2 mr-0 mb-5 ml-2 mr-2 pt-2 pb-4 pr-5 w-100">
      
      <p class="mx-3 mt-2 mb-2 font-weight-bold text-uppercase text-secondary"> Catégories : </p>
      <% @tags.sort_by(&:name).each do |tag| %>
          <% if (tag.projects.published.count + tag.projects.finished.count) > 0 %>
          <p class="mx-1 my-1"><%= link_to "#{tag.name}  (#{(tag.projects.published.count + tag.projects.finished.count) })", tag_path(tag.name), :class =>"tag-filter" %></p>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-md-10 ml-0 pl-0 offset">
      <div class="my-3 text-center">
        <h2 class="text-uppercase"> Projets à venir </h2>
      </div>
      <div class="container my-4">
          <div class="row my-4">
            <% @projects.sort_by(&:start_date).each do |project| %>
              <% if project.state == "published" %>
                <%= render 'project_card', project: project %>
              <%end %>
            <%end %>
          </div>
      </div>

      <hr class="my-2">
      <div class="mt-5 mb-5" >
        <%= render 'layouts/CTA_owner' %>
      </div>
      <hr class="my-2">

    
      <div class="my-3 text-center">
        <h2 class="text-uppercase">Projets passés</h2>

        <div class="container my-4">
            <div class="row my-4">
              <% @projects.sort_by(&:start_date).each do |project| %>
                <% if project.state == "finished" %>
                  <%= render 'project_card', project: project %>
                <%end %>
              <%end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_resources.html.erb
<div class="tab-pane" id="resources">
	<div class="container-fluid">

<div class="card no-border">
  <div class="card-body">
    <h5 class="card-title">Travailler en remote</h5>
    <h5 class="card-title">Nos conseils pour réussir le projet à distance</h5>
    <p class="card-text">La clé : communiquer ! De nombreux outils gratuits sont à disposition collaborer avec votre groupe.</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item text-muted">Appels / Partage d'écran : Whereby, Zoom, Hangouts ...</li>
    <li class="list-group-item text-muted">Chat / Partage de fichiers : Slack</li>
    <li class="list-group-item text-muted">Travail collaboratif : Suite Google, Trello</li>
  </ul>
  <div class="card-body">
  	<%= link_to 'Podcast : travailler en remote', "https://www.welcometothejungle.com/fr/articles/how-to-work-remote", :target => "_blank", class:"card-link"%>
  	<%= link_to 'Guide de survie', "https://www.urbanlinker.com/le-webzine/guide-de-survie-du-remote-worker-185", :target => "_blank", class:"card-link"%>

  </div>
</div>
<br>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Les étapes pour réussir</h5>
    <h5 class="card-title">Comment vous organiser pour construire votre projet</h5>
    <p class="card-text">Le business plan sera la base de votre projet qui vous permettra d'élaborer votre projet. Nous vous recommandons <%= link_to 'cette ressource', "https://www.thebusinessplanshop.com/blog/fr/entry/structure_business_plan", :target => "_blank" %>qui vous servira de base pour créer votre projet.</p>
    <p class="card-text">Vous devrez livrer un pdf de ce plan, ainsi qu'une présentation PTT reprenant les points clés.</p>
  </div>
  <div class="card-body">
  	<%= link_to 'Réaliser un SWOT', "https://www.marketing-strategie.fr/2012/10/03/3409/", :target => "_blank", class:"card-link"%>


  </div>
</div>


	</div>
</div>

app/views/projects/_smallheroimage.html.erb
<div class="jumbotron" >
<div class="hero-text" id="homepage-jumbotron">
  <h1>Envie d'entreprendre?</h1>
  <br>
<br>
  <%= link_to "Get tickets", root_path, :class =>"btn btn-lg btn-primary" %>
</div>
</div> 

app/views/projects/edit.html.erb
<div class="container mt-5 mb-5">
  <div class="row my-5">
    <div class="col-md-7 shadow mx-4 px-3">
      <div class="form-group">
        <% if @project.state == "draft" %>
        <h1 class="headline m-4 px-2 py-2">Modifier votre projet </h1>
        <h5 class="mx-4 my-4 px-2 py-2">Après la publication, il ne sera plus possible de modifier votre projet.</h5>
        <div class="field mx-4 my-5 px-4">
          <%if @project.image.attached?%>
            <%= image_tag url_for(@project.banner), alt: 'project image', class:"my-4 mx-4" %>
          <%else%>
            <%= image_tag asset_path("no-image.jpg"), class:"my-4 mx-4", alt: "placeholder",width: '500'%>
          <%end%>
          <div class="my-4">
            <%= render 'images/images_form', project: @project %>
          </div>
        </div>
        <%= form_tag url_for(action: 'update'), method: "patch" do %>
        <div class="field mx-4 my-5 px-4">
          <p><span class="font-weight-bold mr-3">Vous avez choisi le package :</span> <%= @project.package.title %></p>
            <%= label_tag 'Souhaitez-vous changer de package ?' %>
            <div class="grey-box my-3 p-2">
              <% @packages.each do |package| %>
              <div class="my-4 px-4"><%= radio_button_tag 'package_id', package.id, required: true, class: 'form-check-radio' %><span class='mx-3'><%=package.title%></span><span class='price'><%= (package.price_owner.to_f / 100)%>€</span></div>
              <%end%>
            </div>
          </div>
          <div class="field mx-4 my-5 px-4">
            <%= label_tag 'Modifier le titre de votre projet (max 100 caractères) :' %>
            <%= text_field_tag :title, @project.title, required: true, class:'form-control smallform' %>
          </div>
          <div class="field mx-4 my-5 px-4">
          <%= label_tag 'Choisir une ou plusieurs catégories :'%>
          <%= select_tag(:tag_ids, options_for_select(Tag.order(:name).map {|tag| [tag.name, tag.id]}), multiple: true, class:"form-control regularform")%>
          </div>

          <div class="field mx-4 my-5 px-4">
            <%= label_tag 'Modifier votre brève description (max 200 caractères) :' %>
            <%= text_area_tag :short_description, @project.short_description, required: true, class:'form-control smallform' %>
          </div>

          <% if @project.long_description %>
          <div class="field mx-4 my-5 px-4">
            <%= label_tag 'Description complète (max 1500 caractères) :' %>
            <%= text_area_tag :long_description, @project.long_description, required: true, size: "24x10", class:'form-control smallform' %>
          </div>
          <%else%>
          <div class="field mx-4 my-5 px-4">
            <%= label_tag 'Description complète (max 1500 caractères) :' %>
            <%= text_area_tag :long_description,  nil, placeholder:'En détails :',required: true, size: "24x10", class:'form-control smallform' %>
          </div>
          <%end%>

          <div class="field mx-4 my-5 px-4">
            <%= label_tag "Date de début souhaitée :" %>
            <%= datetime_select("project", "start_date",order: [:day, :month, :year], start_year: 2020, selected: @project.start_date) %>
          </div>

          <div class="field mx-4 my-5 px-4">
            <%= label_tag "Nombre maximum de participants souhaité :" %>
            <%= select_tag(:attendees_goal, options_for_select([['1', 1], ['2', 2], ['3', 3],['4', 4],['5', 5]], @project.attendees_goal ))%>
          </div>  

          <div class="mx-4 my-5 px-4 d-flex justify-content-center">
          <%= submit_tag "Enregistrer mon brouillon", name: "save", class: "btn btn-dark btn-primary mx-2"%>
          <%= submit_tag "Soumettre mon projet", name: "publish", class: "btn btn-dark btn-secondary mx-2"%>
          </div>
        </div>
        <%end%>
        <%else%>
        <p>Vous avez soumis votre projet à la publication, il n'est plus possible d'y apporter des modifications.</p>
        <%end%>
    </div>
    <div class="col-3">
      <div class="my-5 p-5">
        <div class="my-3"><%= image_tag asset_path("inspiration.svg"), alt: "Rocket image", width: 390 %></div>
      </div>
    </div>
  </div>
</div>
<br>

app/views/projects/index.html.erb
<%= render 'projectslist', projects: @projects %>

app/views/projects/ongoing_project.html.erb
<div class="tab-content">
  <%= render 'introduction'%>
  <%= render 'group'%>
  <%= render 'resources'%>
  <%= render 'chat'%>
</div>

app/views/projects/show.html.erb
<div class="container mt-1">
	<div class="row">
		<div class="col-md-8 mb-4 pb-4">
			<div class="d-flex justify-content-center my-4">
				<%if @project.image.attached?%>
					<%= image_tag @project.banner, alt: 'project image', class:"my-4 mx-4" %>
					<div class="product-image text-center my-4">
						<% if current_user == @project.owner %>
							<%= link_to "Changer l'image", edit_project_path(@project.id)%>
						<%end%>
					</div>
				<%else%>
					<%= image_tag("no-image.jpg", class:"my-4 mx-4", alt: "placeholder")%>
					<div class="product-image text-center my-4">
						<% if current_user == @project.owner %>
							<%= render 'images/images_form', project: @project %>
						<%end%>
					</div>
				<%end%>
			</div>
			<div class="product-details shadow p-3 mt-4 mb-5 bg-white rounded">
				<div class="pd-title text-center">
					<h1 class="text-primary my-4"> Projet : <%= @project.title.capitalize %> </h1>
					<p class="my-4"><%= raw @project.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(' ') %></p>
				</div>

				<div class="container pd-desc p-5 mb-4">
					<% if @project.state == "published" ||  @project.state == "finished" %>
						<h4>Le projet en 2 mots </h4>
						<p><%= @project.short_description%></p>
					<br>
						<h4>Description détaillée du projet </h4>
							<%if user_signed_in?%>
								<p><%= @project.long_description %> </p>
							<%else%>
								<p><%= link_to 'Connectez-vous', user_session_path%> pour voir cette information.</p>
							<%end%>
					<br>
					<h4>Projet proposé par : </h4>
					<p><%= @project.owner.first_name.capitalize %> <%= @project.owner.last_name[0].capitalize %> </p>
					<br>
					<h4>Dates : </h4>
					<p>Commence le <%= @project.start_date.strftime("%d/%m/%Y à %I:%M") %> </p>
					<p>Termine le <%= @project.end_date.strftime("%d/%m/%Y à %I:%M") %> </p>
					<br>
					<h4>Places disponibles :  <%= @project.attendees_goal.to_i - @project.attendees.length.to_i %></h4><br>
					<h4>Participants : </h4>
						<% if user_signed_in? %> 
							<% if @project.attendees.length > 0 %>
								<% @project.attendees.each do |participant|%>
									<ul>
										<p><li><%= participant.first_name.capitalize %> <%=participant.last_name[0].capitalize %></li></p>
									</ul>
								<% end %>
							<% else %>
							<p>Il n'y a aucun participant pour le moment.</p>
							<% end %>
						<%else%>
							<p>Connectez-vous pour avoir accès à la liste des participants.</p>
							<p><%= link_to 'Connectez-vous', user_session_path %> pour voir cette information.</p>
						<%end%>
					<br>
					<h4 class="text-primary">Prix :</h4>
					<p><%= @project.package.price_attendee.to_f / 100 %> €</p>
					<br>
					<% end %>
					
					<% if @project.state == "published" %>
            <% if @project.full? %>
              <p class="text-uppercase"> Complet</p>
            <% elsif user_signed_in? %>
               <% if @user_attendance %>
                <p>Vous êtes inscrit à ce projet.</p>
              <% elsif current_user.is_available?(@project) == false %>
                <p>Vous êtes déjà inscrit à un projet sur ces dates.</p>

              <% else %>
                <%= button_to "S'inscrire à ce projet", new_project_attendance_path(@project.id), method: 'get', class:"btn btn-primary"%>
              <% end %>
					  <%else%>
					    <%= button_to "S'inscrire à ce projet", new_project_attendance_path(@project.id), method: 'get', class:"btn btn-primary"%>
						<%end%>
					<%elsif @project.state == "finished"%>
						<p class='my-3'>Ce projet est terminé.</p>
						<p class="my-3"><%= button_to "Voir les autres projets", projects_path, method: 'get', class:"btn btn-secondary my-4" %></p>
					<% end %>
						<% if current_user == @project.owner%>
							<%= render 'ownerproject' %>
								<% if @project.state == "draft" %>
									<p class="my-3">Votre projet n'est pas encore publié : vous devez le compléter et acheter un package pour qu'il soit publié.</p>
									<%= link_to "Editer votre projet", edit_project_path(@project.id), class:"btn btn-sm btn-primary my-3 mx-3"%>
								<% end %> 
							<%= link_to "Créer un nouveau projet", new_project_path, class:"btn btn-sm btn-secondary my-3 mx-3"%>
						<% end %>
				</div>
			</div>
		</div>

		<div class="col-4 my-5">
			<div class="text-center my-4">
				<h5>Projet proposé par :</h5>
				<% if @project.owner.avatar.attached? %>
					<%= image_tag url_for(@project.owner.thumbnail), alt: 'avatar', class:"avatar-small img-circle img-thumbnail my-3" %>
					<% else %>
						<%= image_tag asset_path("avatar_2x.png"), class:"avatar-small img-circle img-thumbnail my-3", alt:"avatar"%>
					<%end%>
					<h6 class="text-secondary"><%= @project.owner.first_name.capitalize %> <%= @project.owner.last_name.capitalize %> </h6>
					<%= link_to "Voir son profil ", user_path(@project.owner.id), :class =>"btn btn-sm btn-primary" %>
			</div>

				<div class="text-center p-5 font-small my-4">
					<h6>Ses compétences :</h6>
						<% if @project.owner.skills.length >= 1 %>
							<p><%= @skill_primary.skill.title %></p>
						<% else %>
							<p>Ce membre n'a pas encore indiqué ses compétences.</p>
							<% if current_user == @project.owner%>
								<%= link_to "Modifier", edit_user_path(current_user.id), :class =>"btn btn-sm btn-dark" %>
							<%end%>
						<%end%>
						<% if @project.owner.skills.length >= 2 %>
							<p><%= @skill_secondary.skill.title %></p>
						<%end%>
				</div>

			<div class="text-center my-4">
				<p>Partager ce projet sur </p>
				<%= link_to image_tag('https://www.facebook.com/images/fb_icon_325x325.png', height: '60', width: '60'), 'http://www.facebook.com/sharer.php?u=https://dazzle-yourself.herokuapp.com'+request.fullpath, :target => :blank %>
			</div>
		</div>
	</div>

</div>