config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'static#home'
  get 'homepage', to:'static#homepage'
  get 'myproject', to:'projects#ongoing_project'
  get 'tags/:tag', to: 'projects#index', as: :tag
  get 'aboutus', to:'static#aboutus'

  resources :posts do
    resources :comments
  end

  resources :users, only: [:show] do
    resources :avatars, only: [:new, :create]
  end

  resources :projects, only: [:edit] do
    resources :images, only: [:new, :create]
  end


  resources :users do
    resources :skill_setups
  end

  resources :projects do
    resources :charges, path: 'paiement'
    resources :attendances, path: 'inscription'
  end

    namespace :admin do
    root 'admin#index'
    resources :users, :projects, :project_submissions
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  include AASM
  belongs_to :project
  belongs_to :attendee, foreign_key: 'attendee_id', class_name: "User"
  # after_create :confirmation_send

aasm column: :state do
  state :pending, initial: true
  state :paid
  state :cancelled

  event :pay do
    transitions from: :pending, to: :paid
  end
  event :cancel do
    transitions from: :paid, to: :cancelled
  end

end


  def confirmation_send
    UserMailer.confirmation_participation_email(self.project, self.attendee).deliver_now
    UserMailer.new_participation_email(self.project, self.project.owner, self.attendee).deliver_now
  end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user


  validates :comment,
  presence: true,
  length: { in: 1..1000}


end

app/models/package.rb
class Package < ApplicationRecord
  has_many :projects

  validates :title,
  presence: true,
  length: { in: 3..50}

  validates :price_attendee,
  presence: true,
  numericality: { greater_than: 100 }


  validates :price_owner,
  presence: true,
  numericality: { greater_than: 100 }

  validates :number_of_days,
  presence: true,
  numericality: { greater_than: 0 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :project
  has_many :comments, dependent: :destroy

  validates :title,
  presence: true,
  length: { in: 3..100}

  validates :content,
  presence: true,
  length: { in: 3..1500}
end

app/models/project.rb
class Project < ApplicationRecord
  include AASM
  belongs_to :owner, foreign_key: 'owner_id', class_name: "User"
  belongs_to :package
  has_many :attendances, dependent: :destroy
  has_many :attendees, class_name: "User", through: :attendances
  has_one_attached :image
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  # after_update :confirmation_email


  validates :title,
  presence: true,
  length: { in: 3..100}

  validates :short_description,
  presence: true,
  length: { in: 5..140}

  validates :attendees_goal,
  presence: true,
  numericality: { greater_than: 1, less_than: 6 }
  
  aasm column: :state do
    state :draft, initial: true
    state :submitted
    state :paid
    state :published
    state :finished

    event :submit do
      transitions from: :draft, to: :submitted
    end
    event :pay do
      transitions from: :submitted, to: :paid
    end
    event :publish do
      transitions from: :paid, to: :published
    end
    event :unpublish do
      transitions from: :published, to: :paid
    end
    event :end do
      transitions from: :published, to: :finished
    end
  end



  def ongoing?
      self.start_date <= Time.zone.now && self.end_date >= Time.zone.now
  end

  def end_date
    self.start_date + (self.package.number_of_days * 86400)
  end

  def confirmation_email
    if self.state == "paid"
      UserMailer.confirmation_charge_email(self, self.owner).deliver_now
    elsif self.state == "published" 
      UserMailer.project_published_email(self, self.owner).deliver_now
      UserMailer.reminder_participation_email(self, self.owner).deliver_later(wait_until: (self.start_date - 259200))

      self.attendees.each do |attendee|
        UserMailer.reminder_participation_email(self, attendee).deliver_later(wait_until: (self.start_date - 259200))
      end
    end
  end

  def banner
    return self.image.variant(resize: "770x433!")
  end
  
  def full?
    if self.attendees.length.to_i >= self.attendees_goal.to_i
      return true
    else
      return false
    end
  end

  def self.tagged_with(name)
    Tag.find_by!(name: name).projects
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :skill_setups, dependent: :destroy
  
  validates :title,
  presence: true,
  length: { in: 4..80}
end

app/models/skill_setup.rb
class SkillSetup < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end
 

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :projects, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :skill_setups, dependent: :destroy
  has_many :skills, through: :skill_setups
  has_many :attendances, foreign_key: 'attendee_id', dependent: :destroy
  has_many :projects, through: :attendances
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :avatar


  # after_create :welcome_send


  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end


  def is_available?(project)
    attendee_projects = Attendance.where(attendee: self)
    owner_projects = Project.where(owner: self)
    project_dates = (project.start_date.strftime("%d/%m/%Y").to_datetime..project.end_date.strftime("%d/%m/%Y").to_datetime)

    unavailable_dates = []

    attendee_projects.each do |attendance|
      (attendance.project.start_date.strftime("%d/%m/%Y").to_datetime..attendance.project.end_date.strftime("%d/%m/%Y").to_datetime).each do |date|
        unavailable_dates << date
      end
    end

    owner_projects.each do |project_o|
      (project_o.start_date.strftime("%d/%m/%Y").to_datetime..project_o.end_date.strftime("%d/%m/%Y").to_datetime).each do |date|
        unavailable_dates << date
      end
    end

    if project_dates.any? {|project_date| unavailable_dates.include?(project_date) }
      return false
    else
      return true
    end

  end

  def ongoing_project

    projects_as_attendee = Attendance.where(attendee: self, state: "paid").map {|a| a.project }.compact
    projects_as_owner = Project.where(owner: self, state: "published").map {|project| project }.compact

    projects = projects_as_attendee + projects_as_owner

    if projects.length > 0
      projects.map {|project| project.ongoing? ? project : nil }.compact
    end
  end


  def thumbnail
    return self.avatar.variant(resize: "200x200!")
  end


  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'error' then "alert-danger"
      when 'alert' then "alert-warning"
    end
  end

  def ownership(user)
    if Project.where(owner: user).length > 0
      return true
    end
  end

  def attendance(user)
    if Attendance.where(attendee: user).length > 0
      return true
    end
  end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def attendance(project)
    if Attendance.find_by(attendee: current_user, project: project)
      return true
    end
  end

  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admin/index.html.erb
<%= render 'kpi_cards' %>
<%= render 'admin/projects/submissions', projects: @projects %>

app/views/layouts/_CTA_attendee.html.erb
<div class="wrapper">
    <%= link_to projects_path, class: "cta" do%>
      <span>VOIR TOUS LES PROJETS</span>
    <span>
      <svg width="66px" height="43px" viewBox="0 0 66 43" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g id="arrow" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
          <path class="one" d="M40.1543933,3.89485454 L43.9763149,0.139296592 C44.1708311,-0.0518420739 44.4826329,-0.0518571125 44.6771675,0.139262789 L65.6916134,20.7848311 C66.0855801,21.1718824 66.0911863,21.8050225 65.704135,22.1989893 C65.7000188,22.2031791 65.6958657,22.2073326 65.6916762,22.2114492 L44.677098,42.8607841 C44.4825957,43.0519059 44.1708242,43.0519358 43.9762853,42.8608513 L40.1545186,39.1069479 C39.9575152,38.9134427 39.9546793,38.5968729 40.1481845,38.3998695 C40.1502893,38.3977268 40.1524132,38.395603 40.1545562,38.3934985 L56.9937789,21.8567812 C57.1908028,21.6632968 57.193672,21.3467273 57.0001876,21.1497035 C56.9980647,21.1475418 56.9959223,21.1453995 56.9937605,21.1432767 L40.1545208,4.60825197 C39.9574869,4.41477773 39.9546013,4.09820839 40.1480756,3.90117456 C40.1501626,3.89904911 40.1522686,3.89694235 40.1543933,3.89485454 Z" fill="#FFFFFF"></path>
          <path class="two" d="M20.1543933,3.89485454 L23.9763149,0.139296592 C24.1708311,-0.0518420739 24.4826329,-0.0518571125 24.6771675,0.139262789 L45.6916134,20.7848311 C46.0855801,21.1718824 46.0911863,21.8050225 45.704135,22.1989893 C45.7000188,22.2031791 45.6958657,22.2073326 45.6916762,22.2114492 L24.677098,42.8607841 C24.4825957,43.0519059 24.1708242,43.0519358 23.9762853,42.8608513 L20.1545186,39.1069479 C19.9575152,38.9134427 19.9546793,38.5968729 20.1481845,38.3998695 C20.1502893,38.3977268 20.1524132,38.395603 20.1545562,38.3934985 L36.9937789,21.8567812 C37.1908028,21.6632968 37.193672,21.3467273 37.0001876,21.1497035 C36.9980647,21.1475418 36.9959223,21.1453995 36.9937605,21.1432767 L20.1545208,4.60825197 C19.9574869,4.41477773 19.9546013,4.09820839 20.1480756,3.90117456 C20.1501626,3.89904911 20.1522686,3.89694235 20.1543933,3.89485454 Z" fill="#FFFFFF"></path>
          <path class="three" d="M0.154393339,3.89485454 L3.97631488,0.139296592 C4.17083111,-0.0518420739 4.48263286,-0.0518571125 4.67716753,0.139262789 L25.6916134,20.7848311 C26.0855801,21.1718824 26.0911863,21.8050225 25.704135,22.1989893 C25.7000188,22.2031791 25.6958657,22.2073326 25.6916762,22.2114492 L4.67709797,42.8607841 C4.48259567,43.0519059 4.17082418,43.0519358 3.97628526,42.8608513 L0.154518591,39.1069479 C-0.0424848215,38.9134427 -0.0453206733,38.5968729 0.148184538,38.3998695 C0.150289256,38.3977268 0.152413239,38.395603 0.154556228,38.3934985 L16.9937789,21.8567812 C17.1908028,21.6632968 17.193672,21.3467273 17.0001876,21.1497035 C16.9980647,21.1475418 16.9959223,21.1453995 16.9937605,21.1432767 L0.15452076,4.60825197 C-0.0425130651,4.41477773 -0.0453986756,4.09820839 0.148075568,3.90117456 C0.150162624,3.89904911 0.152268631,3.89694235 0.154393339,3.89485454 Z" fill="#FFFFFF"></path>
        </g>
      </svg>
    </span> 
  <% end %>
</div>

app/views/layouts/_CTA_owner.html.erb
<div class="wrapper">
    <%= link_to new_project_path, class: "cta" do%>
    <span>CRÉER UN PROJET</span>
    <span>
      <svg width="66px" height="43px" viewBox="0 0 66 43" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g id="arrow" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
          <path class="one" d="M40.1543933,3.89485454 L43.9763149,0.139296592 C44.1708311,-0.0518420739 44.4826329,-0.0518571125 44.6771675,0.139262789 L65.6916134,20.7848311 C66.0855801,21.1718824 66.0911863,21.8050225 65.704135,22.1989893 C65.7000188,22.2031791 65.6958657,22.2073326 65.6916762,22.2114492 L44.677098,42.8607841 C44.4825957,43.0519059 44.1708242,43.0519358 43.9762853,42.8608513 L40.1545186,39.1069479 C39.9575152,38.9134427 39.9546793,38.5968729 40.1481845,38.3998695 C40.1502893,38.3977268 40.1524132,38.395603 40.1545562,38.3934985 L56.9937789,21.8567812 C57.1908028,21.6632968 57.193672,21.3467273 57.0001876,21.1497035 C56.9980647,21.1475418 56.9959223,21.1453995 56.9937605,21.1432767 L40.1545208,4.60825197 C39.9574869,4.41477773 39.9546013,4.09820839 40.1480756,3.90117456 C40.1501626,3.89904911 40.1522686,3.89694235 40.1543933,3.89485454 Z" fill="#FFFFFF"></path>
          <path class="two" d="M20.1543933,3.89485454 L23.9763149,0.139296592 C24.1708311,-0.0518420739 24.4826329,-0.0518571125 24.6771675,0.139262789 L45.6916134,20.7848311 C46.0855801,21.1718824 46.0911863,21.8050225 45.704135,22.1989893 C45.7000188,22.2031791 45.6958657,22.2073326 45.6916762,22.2114492 L24.677098,42.8607841 C24.4825957,43.0519059 24.1708242,43.0519358 23.9762853,42.8608513 L20.1545186,39.1069479 C19.9575152,38.9134427 19.9546793,38.5968729 20.1481845,38.3998695 C20.1502893,38.3977268 20.1524132,38.395603 20.1545562,38.3934985 L36.9937789,21.8567812 C37.1908028,21.6632968 37.193672,21.3467273 37.0001876,21.1497035 C36.9980647,21.1475418 36.9959223,21.1453995 36.9937605,21.1432767 L20.1545208,4.60825197 C19.9574869,4.41477773 19.9546013,4.09820839 20.1480756,3.90117456 C20.1501626,3.89904911 20.1522686,3.89694235 20.1543933,3.89485454 Z" fill="#FFFFFF"></path>
          <path class="three" d="M0.154393339,3.89485454 L3.97631488,0.139296592 C4.17083111,-0.0518420739 4.48263286,-0.0518571125 4.67716753,0.139262789 L25.6916134,20.7848311 C26.0855801,21.1718824 26.0911863,21.8050225 25.704135,22.1989893 C25.7000188,22.2031791 25.6958657,22.2073326 25.6916762,22.2114492 L4.67709797,42.8607841 C4.48259567,43.0519059 4.17082418,43.0519358 3.97628526,42.8608513 L0.154518591,39.1069479 C-0.0424848215,38.9134427 -0.0453206733,38.5968729 0.148184538,38.3998695 C0.150289256,38.3977268 0.152413239,38.395603 0.154556228,38.3934985 L16.9937789,21.8567812 C17.1908028,21.6632968 17.193672,21.3467273 17.0001876,21.1497035 C16.9980647,21.1475418 16.9959223,21.1453995 16.9937605,21.1432767 L0.15452076,4.60825197 C-0.0425130651,4.41477773 -0.0453986756,4.09820839 0.148075568,3.90117456 C0.150162624,3.89904911 0.152268631,3.89694235 0.154393339,3.89485454 Z" fill="#FFFFFF"></path>
        </g>
      </svg>
    </span> 
  <% end %>
</div>

app/views/layouts/_CTA_projectnew.html.erb
<div class="wrapper">
  <%= link_to new_project_path, class: "cta" do%>
    <span>CRÉER UN PROJET</span>
    <span>
      <svg width="66px" height="43px" viewBox="0 0 66 43" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g id="arrow" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
          <path class="one" d="M40.1543933,3.89485454 L43.9763149,0.139296592 C44.1708311,-0.0518420739 44.4826329,-0.0518571125 44.6771675,0.139262789 L65.6916134,20.7848311 C66.0855801,21.1718824 66.0911863,21.8050225 65.704135,22.1989893 C65.7000188,22.2031791 65.6958657,22.2073326 65.6916762,22.2114492 L44.677098,42.8607841 C44.4825957,43.0519059 44.1708242,43.0519358 43.9762853,42.8608513 L40.1545186,39.1069479 C39.9575152,38.9134427 39.9546793,38.5968729 40.1481845,38.3998695 C40.1502893,38.3977268 40.1524132,38.395603 40.1545562,38.3934985 L56.9937789,21.8567812 C57.1908028,21.6632968 57.193672,21.3467273 57.0001876,21.1497035 C56.9980647,21.1475418 56.9959223,21.1453995 56.9937605,21.1432767 L40.1545208,4.60825197 C39.9574869,4.41477773 39.9546013,4.09820839 40.1480756,3.90117456 C40.1501626,3.89904911 40.1522686,3.89694235 40.1543933,3.89485454 Z" fill="#FFFFFF"></path>
          <path class="two" d="M20.1543933,3.89485454 L23.9763149,0.139296592 C24.1708311,-0.0518420739 24.4826329,-0.0518571125 24.6771675,0.139262789 L45.6916134,20.7848311 C46.0855801,21.1718824 46.0911863,21.8050225 45.704135,22.1989893 C45.7000188,22.2031791 45.6958657,22.2073326 45.6916762,22.2114492 L24.677098,42.8607841 C24.4825957,43.0519059 24.1708242,43.0519358 23.9762853,42.8608513 L20.1545186,39.1069479 C19.9575152,38.9134427 19.9546793,38.5968729 20.1481845,38.3998695 C20.1502893,38.3977268 20.1524132,38.395603 20.1545562,38.3934985 L36.9937789,21.8567812 C37.1908028,21.6632968 37.193672,21.3467273 37.0001876,21.1497035 C36.9980647,21.1475418 36.9959223,21.1453995 36.9937605,21.1432767 L20.1545208,4.60825197 C19.9574869,4.41477773 19.9546013,4.09820839 20.1480756,3.90117456 C20.1501626,3.89904911 20.1522686,3.89694235 20.1543933,3.89485454 Z" fill="#FFFFFF"></path>
          <path class="three" d="M0.154393339,3.89485454 L3.97631488,0.139296592 C4.17083111,-0.0518420739 4.48263286,-0.0518571125 4.67716753,0.139262789 L25.6916134,20.7848311 C26.0855801,21.1718824 26.0911863,21.8050225 25.704135,22.1989893 C25.7000188,22.2031791 25.6958657,22.2073326 25.6916762,22.2114492 L4.67709797,42.8607841 C4.48259567,43.0519059 4.17082418,43.0519358 3.97628526,42.8608513 L0.154518591,39.1069479 C-0.0424848215,38.9134427 -0.0453206733,38.5968729 0.148184538,38.3998695 C0.150289256,38.3977268 0.152413239,38.395603 0.154556228,38.3934985 L16.9937789,21.8567812 C17.1908028,21.6632968 17.193672,21.3467273 17.0001876,21.1497035 C16.9980647,21.1475418 16.9959223,21.1453995 16.9937605,21.1432767 L0.15452076,4.60825197 C-0.0425130651,4.41477773 -0.0453986756,4.09820839 0.148075568,3.90117456 C0.150162624,3.89904911 0.152268631,3.89694235 0.154393339,3.89485454 Z" fill="#FFFFFF"></path>
        </g>
      </svg>
    </span> 
  <% end %>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
    <div class="alert alert-dismissible <%= bootstrap_class_for_flash(type) %> m-0" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p style="font-size: 15px;"><%= msg %></p>
    </div>
  <% end %>

app/views/layouts/_header.html.erb
<nav id="mainNav" class="navbar navbar-expand-lg navbar-dark sticky-top navbar-shrink">
  <div class="container">
    <%= link_to root_path do %>
    <%= image_tag asset_path("dazzle_logo.png"), alt: "Dazzle logo", height: 68 %>
    <%end%>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse bg-menu" id="navbarResponsive">
      <ul class="navbar-nav text-uppercase mr-auto">
        <li class="nav-item">
          <li><%= link_to "Participer à un projet", projects_path, class:"nav-link" %></li>
        </li>
        <li class="nav-item">
          <li><%= link_to "Proposer un projet", homepage_path, class:"nav-link"%></li>
        </li>

        <li >

        <% if user_signed_in? %>
          <% if attendance(current_user) == true || ownership(current_user) == true %>
            <% if current_user.ongoing_project != nil %>
              <%= link_to '>> PROJET EN COURS', myproject_path, class:"btn btn-sm btn-warning nav-link", method:'get' %>
            <% end %>
          <% end %>
        <%end%>

      </li>
      

      </ul>
      <span class="navbar-nav ml-auto">
        <div class="dropdown">
          <% if user_signed_in? %>
          <a class="nav-link dropdown-toggle" id="dropdownMenuButton" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user", style="margin-right: 12px;color: white;"></i>MON ESPACE</a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li><%= link_to "Mon profil", edit_user_path(current_user.id), class:"dropdown-item"%></li>
            <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class:"dropdown-item"%></li>
          </div>
          <%else%>
          <a class="nav-link dropdown-toggle" id="dropdownMenuButton" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user", style="margin-right: 12px;color: white;"></i>SE CONNECTER</a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li><%= link_to "S'inscrire", new_user_registration_path, class:"dropdown-item" %></li>
            <li><%= link_to "J'ai déjà un compte", new_user_session_path, class:"dropdown-item" %></li>
          </div>
        </div>
        <%end%>
      </span>
    </div>
  </div>
</nav>

app/views/layouts/_header_homepage.html.erb
<nav style id="mainNav" id="colorNavbar" class="navbar navbar-expand-lg navbar-dark sticky-top navbar-shrink">
  <div class="container">
    <%= link_to root_path do %> 
    <%= image_tag asset_path("dazzle_logo.png"), alt: "Dazzle logo", height: 68 %>
    <%end%>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav text-uppercase mr-auto">
        <li class="nav-item">
          <li class="nav-item">
            <li><%= link_to "Home", root_path, class:"nav-link" %></li>
          </li>
          <li><%= link_to "Participer à un projet", projects_path, class:"nav-link" %></li>
        </li>
        <li class="nav-item">
          <li><%= link_to "Créer un projet", new_project_path, class:"nav-link"%></li>
        </li>
        <li >
          <% if user_signed_in? %>
          <% if attendance(current_user) == true || ownership(current_user) == true %>
          <% if current_user.ongoing_project != nil %>
          <%= link_to '>> PROJET EN COURS', myproject_path, class:"btn btn-sm btn-warning nav-link", method:'get' %>
          <% end %>
          <% end %>
          <%end%>
        </li>
        

      </ul>
      <span class="navbar-nav ml-auto">
        <div class="dropdown">
          <% if user_signed_in? %>
          <a class="nav-link dropdown-toggle" id="dropdownMenuButton" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user", style="margin-right: 12px;color: white;"></i>MON ESPACE</a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li><%= link_to "Mon profil", edit_user_path(current_user.id), class:"dropdown-item"%></li>
            <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class:"dropdown-item"%></li>
          </div>
          <%else%>
          <a class="nav-link dropdown-toggle" id="dropdownMenuButton" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user", style="margin-right: 12px;color: white;"></i>SE CONNECTER</a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li><%= link_to "S'inscrire", new_user_registration_path, class:"dropdown-item" %></li>
            <li><%= link_to "J'ai déjà un compte", new_user_session_path, class:"dropdown-item" %></li>
          </div>
        </div>
        <%end%>
      </span>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Dazzle Yourself</title>
  <html lang="fr">
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csp_meta_tag %>


  <%= stylesheet_link_tag 'styles', media: 'all' %>


</head>
<body>
  <body>
    <div id="layoutSidenav">
      <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
          <div class="sb-sidenav-menu">
            <div class="nav">
              <div class="sb-sidenav-menu-heading"></div>
              <div class="row">
                <%= link_to "Dashboard", admin_root_path, class:"nav-link collapsed" %>
                <% if Project.where(state: "paid").length >= 1 %>
                <i class="fas fa-bell", style="color: red;"></i>
                <% end %>
              </div>
              <div class="sb-sidenav-menu-heading">Gestion</div>
              <%= link_to "Gérer les projets", admin_projects_path, class:"nav-link collapsed" %>                              
              <%= link_to "Gérer les utilisateurs", admin_users_path, class:"nav-link collapsed" %>                            
            </div>
          </div>
          <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            <%= current_user.email %>
          </div>
        </nav>
      </div>
      
      <div id="layoutSidenav_content">
        <main>
          <div class="container-fluid">


            <%= yield %>

          </main>
        </div>
        
      </body>
      <script src="https://kit.fontawesome.com/d714c2541d.js" crossorigin="anonymous"></script>
      </html>